- name: Play1
  hosts: QA
  become: yes
  tasks:
   - name: Installing Terraform on Slave
     shell: sudo wget https://raw.githubusercontent.com/lerndevops/labs/master/scripts/installTerraform.sh -P /tmp
     shell: sudo chmod 755 /tmp/installTerraform.sh
     shell: sudo bash /tmp/installTerraform.sh
   - name: Updating repositories
     apt:
      update_cache: yes
   - name: checking Terraform Version
     shell: terraform -v
     register: consoleout
   - debug:
       var: consoleout.stdout_lines
